# Generated by Django 3.2.25 on 2025-01-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0002_auto_20250116_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftersalerequest',
            name='request_type',
            field=models.CharField(choices=[('return', '退货'), ('exchange', '换货'), ('Refund', '仅退款')], max_length=20, verbose_name='售后类型'),
        ),
    ]
