# Generated by Django 3.2.25 on 2025-01-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0003_alter_aftersalerequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailinfo',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='用户评价'),
        ),
        migrations.AddField(
            model_name='orderdetailinfo',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='评分'),
        ),
    ]
